interface TranslationRequirements {
    it: string
}
let translations = new Map<string, TranslationRequirements>([
    ["The background color", { it: "Il colore dello sfondo" }],
    ["A background image", { it: "Una immagine come sfondo" }],
    ["A local video", { it: "Un video locale" }],
    ["A YouTube embed", { it: "Un video di YouTube" }],
    ["Add content", { it: "Aggiungi contenuto" }],
    ["Delete content", { it: "Rimuovi contenuto" }],
    ["Write a YouTube Playlist or Video URL:", { it: "Scrivi l'URL del video o della playlist di YouTube" }],
    ["Apply URL", { it: "Applica URL" }],
    ["Blur", { it: "Blur" }],
    ["Brightness", { it: "Luminosità" }],
    ["Add blur effect also to cards (experimental; can greatly slow down ffmpeg-web)", { it: "Aggiungi l'effetto blur anche alle card (sperimentale; può rallentare di molto ffmpeg-web)" }],
    ["Settings", { it: "Impostazioni" }],
    ["FFmpeg settings:", { it: "Impostazioni di FFmpeg:" }],
    ["Use the following FFmpeg version:", { it: "Usa la seguente versione di FFmpeg:" }],
    ["Suggested", { it: "Consigliato" }],
    ["Might not work on all codecs", { it: "Potrebbe non funzionare con tutti i codec" }],
    ["Enable multithreaded version of FFmpeg WebAssembly", { it: "Usa la versione multi-threaded di FFmpeg" }],
    ["File output:", { it: "File di destinazione:" }],
    ["Use the File System API", { it: "Usa la File System API" }],
    ["Save using a link", { it: "Salva utilizzando un link" }],
    ["Save as a zip file", { it: "Salva come file zip" }],
    ["Hardware acceleration", { it: "Accelerazione hardware" }],
    ["Add arguments before the FFmpeg script to allow hardware acceleration. You can find presets for most hardware acceleration providers in the select below.", { it: "Aggiungi argomenti prima dello script di FFmpeg per utilizzare l'accelerazione hardware. Puoi trovare dei presets per la maggior parte dei fornitori di schede video con accelerazione hardware dal menù di selezione in basso." }],
    ["No hardware acceleration", { it: "Nessuna accelerazione hardware" }],
    ["Custom syntax", { it: "Sintassi personalizzata" }],
    ["Custom arguments:", { it: "Argomenti personalizzati:" }],
    ["You can write custom arguments, that will be put at the start of the ffmpeg script, here.", { it: "Puoi scrivere qui degli argomenti personalizzati da inserire all'inizio dello script di FFmpeg" }],
    ["UI Customization:", { it: "Personalizzazione dell'interfaccia:" }],
    ["Create a new theme:", { it: "Crea un nuovo tema:" }],
    ["You can find all the values you need to edit here. Make sure to save the theme before unloading the page!", { it: "Qui trovi tutti i valori che puoi modificare. Ricordati di salvare il tema prima di chiudere la pagina!" }],
    ["Save theme", { it: "Salva tema" }],
    ["Manage current themes", { it: "Gestisci i temi correnti" }],
    ["Background content:", { it: "Contenuto nello sfondo:" }],
    ["Use as background:", { it: "Utilizza come sfondo:" }],
    ["Screensaver:", { it: "Salvaschermo:" }],
    ["Enable screensaver", { it: "Abilita salvaschermo" }],
    ["Enable screensaver after", { it: "Abilita salvaschermo dopo" }],
    ["Screensaver background:", { it: "Sfondo del salvaschermo:" }],
    ["Available content in the screensaver:", { it: "Contenuto disponibile nel salvaschermo:" }],
    ["Show file name", { it: "Mostra il nome del file" }],
    ["Show conversion progress and console output", { it: "Mostra il progresso della conversione e l'output della console" }],
    ["Enable screensaver in fullscreen mode", { it: "Abilita salvaschermo in modalità a schermo interno" }],
    ["Enable screensaver now", { it: "Abilita adesso il salvaschermo" }],
    ["Enable alerts", { it: "Abilita avvisi" }],
    ["Close alert after", { it: "Chiudi avviso dopo" }],
    ["Reset ignored alerts", { it: "Reimposta gli avvisi ignorati" }],
    ["Advanced file save preferences:", { it: "Preferenze avanzate per il salvataggio dei file:" }],
    ["Keep Blobs saved", { it: "Mantieni salvati i Blob" }],
    ["Immediately delete Blobs after download. Disable this if you aren't able to download files", { it: "Elimina immediatamente i Blob dopo il download. Disabilita quest'opzione se hai problemi nello scaricare i file" }],
    ["Save conversion preferences", { it: "Salva le preferenze di conversione" }],
    ["Custom input:", { it: "Input personalizzato:" }],
    [`Write an argument in the textbox below. Then, click "Add" or press "Tab" to add it as an argument. Click on each argument to delete it.`, { it: `Scrivi un argomento nella casella di testo in basso. Poi clicca su "Aggiungi" oppure premi "Tab" per aggiungerlo come argomento. Clicca su qualsiasi argomento per eliminarlo` }],
    ["You can also add", { it: "Puoi anche aggiungere" }],
    ["that'll be automatically replaced with the file name, and", { it: "che verrà automaticamente sostituito con il nome del file, e" }],
    ["to add a dollar sign.", { it: "per aggiungere il segno del dollaro." }],
    ["Merge files:", { it: "Unisci file:" }],
    ["Files will be merged without re-encoding. Write the output file name, with its extension, below.", { it: "I file vengono uniti senza ricodifica. Scrivi il nome del file finale, con la sua estensione, qui in basso." }],
    ["Keep the album art (or the thumbnail) of the first file. Disable it if there are issues with the conversion.", { it: "Mantieni la copertina (o la miniatura) del primo file. Disabilita se ci sono problemi nella conversione" }],
    ["Convert image(s):", { it: "Converti immagini:" }],
    ["You can convert images to various output formats. You can apply the same filters as the video part", { it: "Puoi convertire le immagini a diversi formati di output. Puoi usare gli stessi filtri del contenuto video." }],
    ["Image output format:", { it: "Formato dell'immagine finale:" }],
    ["Add metadata:", { it: "Aggiungi metadati:" }],
    ["You can edit metadata tags directly from FFmpeg, without re-encoding the file. Choose the metadata from the next tab.", { it: "Puoi modificare i metadati direttamente da FFmpeg, senza ricodificare il file. Scegli i metadati dalla prossima sezione." }],
    ["Keep current metadata", { it: "Mantieni i metadati correnti" }],
    ["Keep album art in MP4 files, disabling custom tags", { it: "Mantieni la copertina nei file MP4, disabilitando i tag personalizzati" }],
    ["Audio output:", { it: "Output dell'audio:" }],
    ["Audio channels:", { it: "Canali audio:" }],
    ["Default", { it: "Predefinito" }],
    ["Mono", { it: "Mono" }],
    ["Stereo", { it: "Stereo" }],
    ["Keep album art", { it: "Mantieni la copertina" }],
    ["Copy all the metadata at the end. Enable this only if FFmpeg, by default, has discarded some metadata. This applies both for video and audio formats.", { it: "Copia tutti i metadati alla fine. Abilita questo solo se FFmpeg, di default, ha eliminato alcuni metadati. Questo viene applicato sia ai formati video che ai formati audio." }],
    ["Add audio filters", { it: "Aggiungi filtri audio" }],
    ["Audio filters:", { it: "Filtri audio:" }],
    ["Audio volume:", { it: "Volume audio:" }],
    ["Change loudness: add", { it: "Cambia rumorosità: aggiungi" }],
    ["decibels", { it: "decibel" }],
    ["Noise removal:", { it: "Rimozione del rumore:" }],
    ["Remove noise:", { it: "Rimuovi rumore:" }],
    ["Custom audio filter:", { it: "Filtro audio personalizzato:" }],
    ["Apply a custom audio filter that follows the FFmpeg syntax:", { it: "Applica un filtro audio personalizzato che segue la sintassi di FFmpeg" }],
    ["Choose bitrate:", { it: "Scegli bitrate:" }],
    ["Choose with a slider", { it: "Scegli con uno slider:" }],
    ["Closer to the left:", { it: "Più vicino a sinistra:" }],
    ["higher quality", { it: "qualità più alta" }],
    ["worse quality", { it: "qualità più bassa" }],
    ["high bitrate", { it: "bitrate più alto" }],
    ["Conversion status:", { it: "Status della conversione:" }],
    ["You'll see here all the logs made by ffmpeg.", { it: "Vedrai qui tutti i log fatti da FFmpeg" }],
    ["File selection:", { it: "Selezione dei file:" }],
    ["Choose files:", { it: "Scegli file:" }],
    ["Choose how multiple files should be managed:", { it: "Scegli come i file multipli dovrebbero essere gestiti" }],
    ["Use only the first file", { it: "Usa solo nel primo file" }],
    ["Add all the files in the output argument", { it: "Aggiungi tutti i file nell'argomento di output" }],
    ["Add the video/audio if it has the same name as the first file", { it: "Aggiungi il video/audio se ha lo stesso nome del primo file" }],
    ["Add the video/audio if it has the same name (for each content)", { it: "Aggiungi il video/audio se ha lo stesso nome (per ogni file)" }],
    ["Execute the same command for each file", { it: "Esegui lo stesso comando per ogni file" }],
    ["Note: the selected files will be overwritten. Please make a copy of them before continuing.", { it: "Nota: i file selezionati verranno sovrascritti. Potrebbe essere utile fare una copia dei file prima di continuare." }],
    ["Select a folder", { it: "Scegli una cartella" }],
    ["Choose output directory", { it: "Scegli la directory di desstinazione" }],
    ["Choose a folder", { it: "Scegli una cartella" }],
    ["Choose a file", { it: "Scegli un file" }],
    ["folder", { it: "cartella" }],
    ["file", { it: "file" }],
    ["Privacy:", { it: "Privacy:" }],
    ["What do you want to do?", { it: "Cosa vorresti fare?" }],
    ["Scroll to see more options", { it: "Scroll per vedere più opzioni" }],
    ["Media encoding", { it: "Codifica multimediale" }],
    ["Custom command", { it: "Comando personalizzato" }],
    ["Merge content", { it: "Unisci contenuto" }],
    ["Convert to image", { it: "Converti immagini" }],
    ["Add metadata", { it: "Aggiungi metadati" }],
    ["If you are re-encoding the media file, you can choose its options. Otherwise, choose the files on the next card", { it: "Se stai ricodificando il file, puoi selezionare le sue opzioni. Oppure, scegli i file nella apposita card" }],
    ["You can choose between lots of formats. Click on the switch to select what media type(s) you want in your final file:", { it: "Puoi scegliere tra molti formati. Clicca sullo slider per selezionare quali file multimediali vuoi nel file finale:" }],
    ["Enable video source", { it: "Abilita sorgente video" }],
    ["Enable audio source", { it: "Abilita sorgente audio" }],
    ["Add metadata:", { it: "Aggiungi metadati:" }],
    ["Choose a metadata from the list below, and add its value.", { it: "Scegli un metadato dalla lista in basso, ed scrivi il suo valore." }],
    ["Custom key", { it: "Chiave personalizzata" }],
    ["Value", { it: "Valore" }],
    ["Add metadata", { it: "Aggiungi metadato" }],
    ["Added metadata:", { it: "Metadati aggiunti" }],
    ["Delete", { it: "Elimina" }],
    ["Add custom album art", { it: "Aggiungi copertina personalizzata" }],
    ["Delete every video track (also the source album art)", { it: "Elimina qualsiasi traccia video (anche la copertina d'origine)" }],
    ["Re-download files", { it: "Riscarica file" }],
    ["Choose from the select below the files to re-download.", { it: "Scegli dal menù di selezione in basso i file da riscaricare." }],
    ["Download file", { it: "Scarica file" }],
    ["Delete Blob from memory", { it: "Elimina il Blob dalla memoria" }],
    ["Trim content:", { it: "Taglia contenuto:" }],
    ["Don't trim content", { it: "Non tagliare il contenuto" }],
    ["Trim content (single timestamp)", { it: "Taglia il contenuto (timestamp singolo)" }],
    ["Trim content (multiple timestamps)", { it: "Taglia il contenuto (timestamp multipli)" }],
    ["Single timestamp settings:", { it: "Impostazioni per il singolo timestamp:" }],
    ["Start:", { it: "Inizio:" }],
    ["End:", { it: "Fine:" }],
    ["Multiple timestamps settings:", { it: "Impostazioni per i timestamp multipli:" }],
    ["Write the multiple timestamps, one for each line. Then, add a divider between the timestamp and the file title", { it: "Scrivi i timestamp multipli, uno per riga. Dopo, aggiungi un divisore tra i timestamp ed il titolo dei file" }],
    ["Divider", { it: "Divisore" }],
    ["Timestamp at the left", { it: "Il timestamp è a sinistra" }],
    ["Automatically add title and track metadata", { it: "Aggiungi automaticamente i metadati del titolo e del numero di traccia" }],
    ["Start from track", { it: "Inizia dalla traccia" }],
    ["Image output:", { it: "Output dell'immagine:" }],
    ["Video output:", { it: "Output del video:" }],
    ["Keep the same FPS", { it: "Mantieni gli stessi FPS" }],
    ["FPS Options:", { it: "Opzioni degli FPS:" }],
    ["Input FPS:", { it: "FPS di origine:" }],
    ["Output FPS:", { it: "FPS di destinazione:" }],
    ["Change aspect ratio and rotation settings", { it: "Cambia l'aspect ratio e le impostazioni di rotazione" }],
    ["Aspect ratio", { it: "Aspect ratio" }],
    [`Put "-1" as the value to skip it when elaborating arguments`, { it: `Metti "-1" come valore per saltarlo durante l'elaborazione delle preferenze` }],
    ["Width:", { it: "Larghezza:" }],
    ["Height:", { it: "Altezza:" }],
    ["Rotation:", { it: "Rotazione:" }],
    ["Don't rotate", { it: "Non ruotare" }],
    ["Rotate", { it: "Ruota di" }],
    ["Change pixel format:", { it: "Cambia il formato dei pixel:" }],
    ["Write the output pixel format. Leave this field blank to apply the default one", { it: "Scrivi il formato dei pixel di destinazione. Lascia questo campo vuoto per applicare quello di default." }],
    ["Add video filters", { it: "Aggiungi filtri video" }],
    ["Video filters:", { it: "Filtri video:" }],
    ["Position", { it: "Posizione" }],
    ["Deinterlace video", { it: "Deinterlaccia video" }],
    ["Video filters:", { it: "Filtri video:" }],
    ["Apply one of the following video filters:", { it: "Applica uno dei seguenti filtri video:" }],
    ["Custom video filter:", { it: "Filtro video personalizzato:" }],
    ["Apply a custom video filter that follows the FFmpeg syntax:", { it: "Applica un filtro video personalizzato che segua la sintassi di FFmpeg:" }],
    ["Conversion text will appear here", { it: "Il testo della conversione apparirà qui" }],
    ["No conversion started", { it: "Nessuna conversione iniziata" }],
    ["The selected conversion (Conversion", { it: "La conversione selezionata (Conversione" }],
    ["has ended!", { it: "è finita!" }],
    ["Converting file:", { it: "Conversione del file:" }],
    ["Close dialog", { it: "Chiudi pop-up" }],
    ["Close", { it: "Chiudi" }],
    ["Do not show this again", { it: "Non mostrare più" }],
    ["Started operation", { it: "È iniziata l'operazione" }],
    [`Change the Operation ID from the "Conversion Status" tab to see the current progress.`, { it: `Cambia l'ID dell'operazione dalla scheda dello "Status di conversione" per vedere il progresso di quest'operazione.` }],
    ["Completed operation", { it: "È stata completata l'operazione" }],
    ["Conversion options:", { it: "Opzioni di conversione:" }],
    ["Alerts", { it: "Avvisi" }],
    ["Cut video:", { it: "Taglia video:" }],
    ["Your media files are locally elaborated, therefore they'll always stay on your device.", { it: "I tuoi file multimediali sono elaborati localmente, e quindi staranno sempre solo sul tuo dispositivo." }],
    ["This website connects to unpkg & Google Fonts only to fetch essential resources to work, and doesn't share any data with them.", { it: "Questo sito si connette ad unpkg e Google Fonts per ottenere risorse essenziali per il suo funzionamento, ma non condivide alcun dato con loro." }],
    ["This website is published under the", { it: "Questo sito è disponibile sotto la" }],
    ["MIT license", { it: "licenza MIT" }],
    ["and you can find (and, if you want, analyze) the", { it: "e puoi trovare (e, se vuoi, analizzare) il" }],
    ["source code on GitHub", { it: "codice sorgente su GitHub" }],
    ["Won't replace duplicate (no access to your device's file system)", { it: "Non sostituirà i duplicati (nessun accesso al file system del dispositivo)" }],
    ["Will replace duplicates (direct access to File System)", { it: "Sostituirà i duplicati (accesso diretto al file system)" }],
    ["Overwrite", { it: "Sovrascrivi" }],
    ["Found existent file", { it: "Trovate un file già esistente" }],
    ["Exit after each timestamp conversion", { it: "Esci dopo ogni conversione del timestamp" }],
    ["Exit after each file conversion", { it: "Esci dopo ogni conversione del file" }],
    ["Move content from top to bottom (and viceversa) every", { it: "Sposta il contenuto dall'alto verso il basso (e viceversa) ogni" }],
    ["Convert only files that ends with (separate multiple extension with |):", { it: "Converti solamente i file che finiscono con (separa più estensioni con |):" }],
    ["Installation", { it: "Installazione" }],
    ["You can install ffmpeg-web as a Progressive Web App, or you can get way higher performances by installing the Electron application. You can find the instructions from the Select below", { it: "Puoi installare ffmpeg-web come una Progressive Web App, o puoi ottenere prestazioni molto più elevate installando l'applicazione Electron. Puoi trovare le istruzioni dal selettore in basso" }],
    ["Download the zip file of the repository:", { it: "Scarica il file zip della repository:" }],
    ["click here", { it: "clicca qui" }],
    ["Extract the files, and make sure to have Node.JS 20 and a native version of FFmpeg installed", { it: "Estrai i file, ed assicurati di aver installato Node.JS 20 e una versione nativa di FFmpeg" }],
    ["Run the following command to install the app:", { it: "Esegui il seguente comando per installare l'app:" }],
    ["And that's done! You can now run the app by writing", { it: "Ed hai finito! Puoi ora eseguire l'app scrivendo" }],
    ["from the command line in that folder", { it: "dalla linea di comando in quella cartella" }],
    [`click on the three dots near the URL bar, and then on "Install as an app"`, { it: `Clicca sui tre puntini vicino alla barra degli URL, e clicca su "Installa come app"` }],
    [`click on the "Install app" icon at the right of the URL address`, { it: `clicca sull'icona "Installa applicazione" a destra dell'URL` }],
    [`share the webpage, and then click on "Add to the home"`, { it: `condividi la pagina, e poi clicca su "Aggiungi alla schermata home"` }],
    ["About this website", { it: "Su questo sito" }],
    ["View on GitHub", { it: "Visualizza su GitHub" }],
    ["Show installation instructions", { it: "Mostra istruzioni di installazione" }],
    ["Hide this card", { it: "Nascondi questa card" }],
    ["Show update changelog", { it: "Mostra il changelog degli aggiornamenti" }],
    ["Change image after:", { it: "Cambia immagine dopo:" }]
])
/**
 * Translate a string
 * @param str the string to translate
 * @returns the translated string, if available
 */
export function getLang(str: string) {
    const translation = translations.get(str);
    return translation ? translation[(localStorage.getItem("ffmpegWeb-SelectedLanguage") as null | "it") ?? navigator.language?.substring(0, 2) as "it"] ?? str : str;
}